# Generated by Django 5.1.4 on 2024-12-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nombre de la persona')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('confirm_email', models.EmailField(max_length=254, verbose_name='confirmacion correo')),
                ('password', models.CharField(max_length=20, verbose_name='contraseña')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Dato persona',
                'verbose_name_plural': 'Datos personas',
                'ordering': ['-created'],
            },
        ),
    ]
