# Generated by Django 5.1.4 on 2024-12-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datosperson_password_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosperson',
            name='cedula',
            field=models.BooleanField(null=True, verbose_name='cedula'),
        ),
    ]
