# Generated by Django 5.1.4 on 2024-12-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datosperson_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosperson',
            name='cedula',
            field=models.FloatField(null=True, verbose_name='cedula'),
        ),
    ]
