# Generated by Django 5.1.4 on 2024-12-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_datosperson_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosperson',
            name='cedula',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='cedula'),
        ),
    ]
