# Generated by Django 5.1.4 on 2024-12-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_datosperson_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosperson',
            name='confirm_email',
        ),
        migrations.RemoveField(
            model_name='datosperson',
            name='email',
        ),
        migrations.RemoveField(
            model_name='datosperson',
            name='password',
        ),
        migrations.RemoveField(
            model_name='datosperson',
            name='password_confirm',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('confirm_email', models.EmailField(max_length=254, verbose_name='confirmacion correo')),
                ('password', models.CharField(max_length=20, verbose_name='contraseña')),
                ('password_confirm', models.CharField(max_length=20, null=True, verbose_name='confirmar contraseña')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.datosperson')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-created'],
            },
        ),
    ]
