# Generated by Django 5.1.4 on 2024-12-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_datosperson_confirm_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosperson',
            name='cedula',
            field=models.IntegerField(null=True, verbose_name='cedula'),
        ),
    ]
